services:
  - type: web
    name: navidrome-music-server
    runtime: docker
    plan: free
    envVars:
      - key: SUPABASE_PROJECT_ID
        value: "qxzhrmpijtsmovcodmzr"
      - key: SUPABASE_SECRET_KEY
        value: "sb_secret_GDMbj6xF4wv16KmUUXHPvA_UlXQBpdg"
      - key: ND_MUSICFOLDER
        value: "http://127.0.0.1:8081/"
      - key: ND_DATAFOLDER
        value: "/tmp/navidrome_cache"
      - key: ND_LOGLEVEL
        value: "info"
